spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${CLEARDB_DATABASE_URL}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

jwt:
  secret: ${JWT_SECRET}
  expirationMs: 3600000
  refreshExpirationMs: 86400000
